name = "Modpack Template"
author = "Merith.TK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ab22d665a56d4ba026899210762e6bf3641be4f35fe8d56ffd4e2ed3d191114"

[versions]
fabric = "0.14.9"
minecraft = "1.19.4"
